package taxonomy;

import generator.configurations.ConfigurationManager;
import generator.configurations.ElasticityConfiguration;

/**
 * <p>Horizontal Elasticity entity that contains a series generated by a Probability Distribution Function(PDF)</p>
 * <p>It can generate series with two PDFs:</p>
 * <ul>
 *     <li>Uniform Distribution</li>
 *     <li>Poisson Distribution</li>
 * </ul>
 * @author Augusto Amarilla
 * @since 9/17/16.
 */
public class HorizontalTaxonomy extends TaxonomyAbstract {
    public HorizontalTaxonomy(ElasticityConfiguration configuration){
        super(configuration);
    }

    public Integer getNextVmQuantity() {
        Integer vmQuantity = this.distribution.getNextValue();

        while (vmQuantity <= 0 || vmQuantity > ConfigurationManager.getInstance().getMaxVmsPerService()) {
            vmQuantity = this.distribution.getNextValue();
        }

        return vmQuantity;
    }
}
